### ISSUE TITLE
Home Education 2021

### ISSUE THREAD

**Issue by andrea2702** [RoBorregos/robocup-home#165]
Deliverables:
- [ ] TDP (Team description paper)
- [ ] Team poster + presentation of technical development

**Task 1**
Visión
- [ ] Detectar bolsa
- [ ] Detectar obstáculos  (personas, objetos pequeños en el piso)

Mecánica
- [ ] Tomar bolsa

Navegación
- [ ] Seguir al operador

Bonus 
- [ ] Volver al punto de inicio
- [ ] Regresar a la arena

**Task 2**
Vision
- [ ] Detectar a la persona

Navegación
- [ ] Moverse frente a la persona
- [ ] Dar ubicacion de la persona

Speech
- [ ] Dar nombre correcto de la persona
- [ ] Dar descripcion correcta de 2 personas
**_Bonus_**
- [ ] Nombre y descripción de tercera persona

**Task 3**
Speech
- [ ] Introducir a 2 invitados  (nombre y bebida favorita)

Navegacion
- [ ] Apuntar al invitado
- [ ] Apuntar a asiento vacio

Vision
- [ ] Detectar un asiento libre

_**Bonus**_
- [ ] Abrir puerta al invitado
- [ ] Sentar a la persona mas vieja en el sofa

**Notas**

**_Set up and demostration_**
7 minutos maximos de set up, presentacion y demostracion
**_Interview and celan up_**
3 minutos para responder preguntas. Durante el tiempo deshacer cambios hechos por el equipo a la pista.
